### ISSUE TITLE
Unused requires are first sorted instead of removed

### ISSUE THREAD

**Issue by Gluestick** [nedap/formatting-stack#151]
## Brief

When there is a require that is both unused and out of order, formatting stack will simply reorder the require without removing it. When running formatting stack a second time, the unused require will be removed.

## Expected behavior

Unused, out of order requires are removed

## Actual behavior

Unused, out of order requires are not removed, but sorted.

## Reproduction steps

Simply add an out-of-order, unused require to an existing file. Stage the changes. Run `format-and-lint-branch!` once, and the require will be sorted. Run it again, and it will be removed.

## Suspected cause

None

**Comment by vemv** [comment]
f-s version?

**Comment by Gluestick** [comment]
@vemv 4.2.0, i.e. latest.

**Comment by vemv** [comment]
Thanks. Can reproduce:

```clj
formatting-stack.branch-formatter=> (mapply strategies/git-diff-against-default-branch (assoc {} :target-branch "master"))
nil
;; stage the changes...
formatting-stack.branch-formatter=> (mapply strategies/git-diff-against-default-branch (assoc {} :target-branch "master"))
("/Users/vemv/formatting-stack/test/functional/formatting_stack/a.clj")
```

**Comment by vemv** [comment]
This has always been the behavior: https://github.com/nedap/formatting-stack/blob/fbb262074e3de814603fc8b64e5fb178e168f261/src/formatting_stack/strategies.clj#L86

The underlying idea is that you should review and stage whatever f-s does - there's always risk of formatters having bugs (e.g. overzealous `:require` removal). That's reflected in the README.

[This](https://github.com/nedap/formatting-stack/pull/147) wip branch will make formatters and strategies more flexible to customize, so per-user tweaks are not out of the equation.

Other than that, f-s should default to safety and assume people use git intentfully.
