### ISSUE TITLE
`git-diff-against-default-branch` accepts non-existing branches as an argument

### ISSUE THREAD

**Issue by vemv** [nedap/formatting-stack#157]
## Expected behavior

For the following input:

```clj
(git-diff-against-default-branch :target-branch "I-dont-exist")
```

...A precondition should fail informing nicely that the given `:target` branch doesn't exist.

## Actual behavior

`nil` is returned, suggesting that the branch exists but there's an empty diff.

## Environment info

4.2.1

**Comment by vemv** [comment]
Currrently` :target-branch` accepts things like `c2e3259c`, `HEAD~2`, `v0.19.0` etc. I'd keep that supprt while still throwing on any non-existing object.

**Comment by thumbnail** [comment]
Good suggestion! We could solve this by trying to parse the ref, if it doesn't resolved (or is ambiguous), throw.
