### ISSUE TITLE
Eastwood: `IndexOutOfBoundsException Method code too large!` unreported

### ISSUE THREAD

**Issue by vemv** [nedap/formatting-stack#159]
## Brief

Given faulty code due to overly large `defprotocol`s, Eastwood stops execution. Prior faults will be reported by f-s, but Eastwood execution will stop there _silently_.

## Expected behavior

* This specific exception is caught and reported, similarly to how we handle reflection warnings
* More generally, if an unexpected ex occurs, it should be reported.
  * This was the behavior until https://github.com/nedap/formatting-stack/pull/116 (`Encountered an exception, which will be printed in the next line` removal)

## Reproduction steps

* Create a `defprotocol` so large that it will create a `IndexOutOfBoundsException Method code too large!`
* Lint that code through f-s
* Be reported of no error whatsoever

## Screenshot, stacktrace, etc

This is the stacktrace of the bad behavior that happens (but the stacktrace itself is never printed)

```
Caused by:
IndexOutOfBoundsException Method code too large!
	clojure.asm.MethodWriter.computeMethodInfoSize (MethodWriter.java:2061)
	clojure.asm.ClassWriter.toByteArray (ClassWriter.java:457)
	clojure.lang.Compiler$ObjExpr.compile (Compiler.java:4668)
	clojure.lang.Compiler$FnExpr.parse (Compiler.java:4106)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7105)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.eval (Compiler.java:7174)
	clojure.lang.Compiler.eval (Compiler.java:7132)
	clojure.core/eval (core.clj:3214)
	clojure.core/eval (core.clj:3210)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--17749 (jvm.clj:585)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:585)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:528)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--17747 (jvm.clj:568)
	clojure.core/mapv/fn--8445 (core.clj:6912)
	clojure.lang.ArrayChunk.reduce (ArrayChunk.java:63)
	clojure.core.protocols/fn--8154 (protocols.clj:136)
	clojure.core.protocols/fn--8154 (protocols.clj:124)
	clojure.core.protocols/fn--8114/G--8109--8123 (protocols.clj:19)
	clojure.core.protocols/seq-reduce (protocols.clj:31)
	clojure.core.protocols/fn--8144 (protocols.clj:75)
	clojure.core.protocols/fn--8144 (protocols.clj:75)
	clojure.core.protocols/fn--8088/G--8083--8101 (protocols.clj:13)
	clojure.core/reduce (core.clj:6828)
	clojure.core/mapv (core.clj:6903)
	clojure.core/mapv (core.clj:6903)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:568)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:528)
```

**Comment by vemv** [comment]
cc/ @thumbnail 

It might be easy to give a reasonable fix to this. Else it's frustrating that f-s behaves like a black box that may or not report faults depending on how you run it (lint project vs lint branch. The latter is more likely to succeed in face of these errors, since only a few ns'es will contain this fault)

**Comment by thumbnail** [comment]
This is because the eastwood doesn't report exceptions in a easily digestible way. The exceptions are passed into the reporter as `:error` (exception) or `:note` as string. I tried fixing it here: https://github.com/jonase/eastwood/pull/332 but that required more effort than anticipated. 

A quick fix could be string-matching the output under the  `:note`-key in the [`reports`-atom ](https://github.com/nedap/formatting-stack/blob/831ffdd5c4b674d2c1af3f18ad0088a3f92f3dcb/src/formatting_stack/linters/eastwood.clj#L33), but that needs some rigid testing

**Comment by vemv** [comment]
Thanks for the quick and accurate response :)

If this is genuinely hard to detect from f-s, maybe Eastwood could introduce a `:rethrow-exceptions?` option.

Do you think that could work / be more easily implemented than https://github.com/jonase/eastwood/pull/332 ?

**Comment by thumbnail** [comment]
rethrowing might break continuit. We run eastwood once with all the files to lint, if it breaks mid-way only half the files are linted. Properly fixing the reporter would mitigate that.

OTOH; rethrowing would ultimately show the error to the user which might be more important. Alternatively we could see if we can run eastwood/lint! once per filename, as we do with clj-kondo for example.

**Comment by vemv** [comment]
> rethrowing might break continuit. We run eastwood once with all the files to lint, if it breaks mid-way only half the files are linted.

This is exactly what happens now.

I also believe that's what happens with vanilla Eastwood (`lein eastwoood`) from what I recall: if encountering this exception, no more files will be analyzed. The ex will be handled somewhat gracefully (Eastwood will report `3 faults, 1 exception` instead of aborting suddenly).

It makes sense: if a proper AST can't be built, why bother analyzing more files? False positives would pile up as info would be missing.

> Alternatively we could see if we can run eastwood/lint! once per filename

Tried some months ago for unrelated reasons, it was far too slow

**Comment by thumbnail** [comment]
> This is exactly what happens now.

That's great 👍 A rethrow-option would def. help out here; we already have (most) of the mechanics in place to get the exception into the reporter and show it to the user.

**Comment by vemv** [comment]
`:rethrow-exceptions?` has been working nicely so this issue can be closed
