### ISSUE TITLE
Cannot gracefully handle lack of :line / :column from linter reports

### ISSUE THREAD

**Issue by vemv** [nedap/formatting-stack#162]
## Brief

Macro-based code doesn't always emit a line/col mapping.

Accordingly, Eastwood reports coming from such code will lack a :line / :column, which will violate our spec:

https://github.com/nedap/formatting-stack/blob/57e4651fa0913bc4a65415c07b86c3e1dac403a2/src/formatting_stack/protocols/spec.clj#L57-L58

## Expected behavior

Linter faults lacking this info are reported like a regular one.

## Actual behavior

They are reported like exceptions instead, having a long stacktrace, Expound report etc.

## Screenshot, stacktrace, etc

```
{:namespace-sym xxxx.login,
    :linter :suspicious-expression,
    :msg
    "dissoc called with 1 args.  (dissoc map) always returns map.  Perhaps there are misplaced parentheses?",
    :uri-or-file-name
    "xxxxxxxxxxxlogin.clj",
    :source :eastwood/suspicious-expression,
    :level :warning,
    :filename
    "xxxxxxxxx.clj",
    "warning-details-url"
    "https://github.com/jonase/eastwood#suspicious-expression",
    :uri
    #object[java.net.URI 0x12110009 "file:xxxxxxxxxxlogin.clj"],
    :loc nil,
    :warning-details-url
    "https://github.com/jonase/eastwood#suspicious-expression"}
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

should contain keys: :column, :line
```

## Environment info

f-s latest

cc/ @thumbnail

**Comment by thumbnail** [comment]
reproduced, pushing a fix
