### ISSUE TITLE
Newlines for import statements

### ISSUE THREAD

**Issue by tcoenraad** [nedap/formatting-stack#165]
## Brief
Lines like

```
  (:import (java.io File)))
```

are not touched by f-s.

## Expected behavior
```
  (:import
   (java.io File)))
```

## Actual behavior
```
  (:import (java.io File)))
```

## Reproduction steps
Create a namespace with the import statement as described above.

**Comment by vemv** [comment]
👋thanks for the report!

Most likely a https://github.com/gfredericks/how-to-ns issue, we could check by playing with its test suite.

**Comment by vemv** [comment]
I have tested this one:

* in practice
* in h-t-n's test-suite
* in f-s' suite 

...and could not repro it. Maybe you forgot to `git add -A` before reformatting?

I'd suggest, we can extend `functional.formatting-stack.formatters.how-to-ns` to cover the case you describe, that way we kill any uncertainty.

And tomorrow if you find a corner case, you could just play with said test.

Btw, there's a new h-t-n! https://github.com/gfredericks/how-to-ns/pull/14#issuecomment-609077533 cc/ @thumbnail

**Comment by tcoenraad** [comment]
> Maybe you forgot to `git add -A` before reformatting?

Likely, I'm now also not able to reproduce it any longer.
