### ISSUE TITLE
improve git tests

### ISSUE THREAD

**Issue by thumbnail** [nedap/formatting-stack#167]
## Problem statement

https://github.com/nedap/formatting-stack/blob/6a82c0d402237ededfa5c7e95eee82e114b3346b/test/integration/formatting_stack/strategies.clj#L24-L28

This hinders running tests during development. It requires commiting files before running the tests which is unexpected and causes (specific) tests to be ignored until the very end. 

## Proposal

Create a tmp folder, which is filled with the needed files by a fixture. This'll ensure a clean sheet while it has no impact on the project's git status.

java has `File#deleteOnExit` which can be leveraged to cleanup even after failure

## Alternatives and comparison

Migrate to integration test, which'll run against known good output of the `git`-commands, without running them in the shell. Would also remove the need for `git` while running the tests.

**Comment by vemv** [comment]
Agreed that the problem is pretty painful. The first proposal sgtm!

**Comment by vemv** [comment]
I gave a quick shot to this and it seems to me that one would have to create a new project (`git init`) from scratch.

That would imply more setup/teardown steps, touching folders _outside the pwd_, etc so it might be excessively intrincate.

WDYT of wrapping the deftest in a `(when (System/getenv "CI") ...`?

**Comment by thumbnail** [comment]
> That would imply more setup/teardown steps

Yes, but a simple `mkdir` + `git init` for setup, and `rm -rf` should suffice. 

> touching folders outside the pwd

This is not needed. Just make sure the folder is `.gitignore`. Locally i verified i could initialise a new git repo inside a ignored folder _inside_ the pwd :)

> WDYT of wrapping the deftest in a `(when (System/getenv "CI")` ...?

This is a fine alternative; but makes testing the git-related changes locally harder, and might throw off new contributors (in case of a passing `lein test` locally, but failing on CI for tests not even in your report.)


I'd prefer to explore the nested repo approach first, but am fine to settle with the pragmatic approach of disabling the tests locally if that doesn't work out.

**Comment by vemv** [comment]
> Yes, but a simple mkdir + git init for setup, and rm -rf should suffice.

Will try sometime soon 👍

**Comment by thumbnail** [comment]
I put a WIP for the suggestion above in [`167-improve-git-tests`](https://github.com/nedap/formatting-stack/tree/167-improve-git-tests). The code is not final in any way.

With that suggestion there's an issue with the `git-diff-against-default-branch`-test: It relies on 'a large, diverse corpus', which is not easy to replicate. 

I think it's okay to test against the f-s repo, as long as we remove the deletion of the file. (which has other coverage either way). WDYT?

**Comment by vemv** [comment]
> as long as we remove the deletion of the file.

I don't understand this part, can you expand?

> WDYT?

Open to all sorts of solutions. Another one that seems acceptable to me is including a specific repo as a git submodule, for satisfying the `large, diverse corpus` part. speced.def maybe?

...Of course git submodules are pinned to a specific sha so the resulting test would be stable.

**Comment by thumbnail** [comment]
> I don't understand this part, can you expand?

I'm suggesting to use the f-s repo for the `git-diff-against-default-branch`-test. While using the temporary repo for all other tests. In order to be able to do so, it shouldn't rely on `assert-pristine-git-status!`. My suggestion is to remove the rename/delete operations from that tests.

An alternative would be to mock the output of the git command instead. Which would make this test less painful too.

**Comment by vemv** [comment]
> My suggestion is to remove the rename/delete operations from that tests.

Decreasing test coverage seems a bad tradeoff to me (for a root issue which boils down to developer convenience)

> An alternative would be to mock the output of the git command instead. 

Similarly I'm not fond of mocking. Mocking tests against our assumptions; those may be partial, incorrect or become outdated over time.

> I'm not a fan of submodules, and I don't think this usecase (parsing git-output) warrants one.

We can agree to disagree here (and simply discard this alternative, because one of us does)

**Comment by vemv** [comment]
Perhaps a lightweight solution would be:

* do not run the tests if the git status is not pristine, **and** the env != CI
* run the tests if the git status is pristine, **or** env == CI

One can observe that the chances of breaking the git functionality are pretty low (because we expect our impl to be right, and accordingly very rarely ever touch it), so _a test occasionally not being run locally_ seems a reasonable tradeoff.

**Comment by thumbnail** [comment]
> Decreasing test coverage seems a bad tradeoff to me (for a root issue which boils down to developer convenience)

Agreed, however, depending on how the code/tests are structured, there's no need for a decreased test-coverage. 

> run the tests if the git status is pristine, or env == CI

While I think this is a good solution for everybody "in the know", it's very opaque to newcomers (or even occasional contributors). In your example a failing test-suite with N cases, will, after a uncomitted fix, run <N tests. 

I'll discuss these options internally and see if there's strong preferences for any solution.

**Comment by thumbnail** [comment]
After some internal discussion, @neominik suggested to do a relative git checkout into a separate for. That solves most outstanding issues with my earlier suggestion (which were manually creating git log and lack of diverse corpus). I'll tinker with the branch and keep this issue updated

**Comment by thumbnail** [comment]
Created a draft PR with the suggestion implemented; https://github.com/nedap/formatting-stack/pull/185
