### ISSUE TITLE
Bump rewrite-clj

### ISSUE THREAD

**Issue by vemv** [nedap/formatting-stack#177]
## Problem statement

https://github.com/clj-commons/rewrite-clj/ got a major refactor, with some breaking changes (albeit minor) and has released its first alpha.

It'd be good to try out said alpha, particularly we have a substantial CI matrix.

I find it important because rewrite-clj is not only a dep of cljfmt, but also of arbitrarily many other deps so one cannot assume that pulling `cljfmt` inherently pulls a compatible version of rewrite-clj. Some of those deps may become part of f-s in a future.

## Proposal

Bump rewrite-clj.

Since it belongs to our :managed dependencies I think it wouldn't make a difference to our consumers.

## Note

For the CI results to be representative one should include include contents that are actually affected by the breaking changes. Example:

https://raw.githubusercontent.com/threatgrid/formatting-stack.alias-rewriter/921e62713f3c664f8bf6fa92d1bcb3e6fec277a5/test-resources/example_one/input.clj

## Alternatives and comparison

* Do nothing
* Create this work as a branch/PR, but don't merge
  * some sort of long-lived branch might help

**Comment by thumbnail** [comment]
Good suggestion 👍 .

Bumping seems fine, could release an alpha if presented with a PR.

**Comment by vemv** [comment]
This won't end up being necessar, cljfmt already bumped rewrite-clj on it own (I wouldn't have expected that to happen so quickly!)

So we can simply bump cljfmt at some point and simply observe that our CI keeps passing.
