### ISSUE TITLE
Setting *print-length* causes requirement sorting to abbreviate your requires

### ISSUE THREAD

**Issue by lennartbuit** [nedap/formatting-stack#192]
## Brief

When you have `*print-length*` set to say 10, formatting causes your requirements to be abbreviated to whatever length you had it set to.

## Expected behavior

`*print-length*` should not affect formatting-stack

## Actual behavior

It does

## Reproduction steps

1. Have an ns with more than `n` requires. 
2. Set `*print-length*` to `n`
3. Run f-s
4. Observe a bunch of `Removing trivial duplicates in `ns` form:` messages
5. Observe your requires to be abbreviated to `[...]` + first `n` requires.

**Comment by vemv** [comment]
Sounds like an issue in https://github.com/gfredericks/how-to-ns, could you check it out?

**Comment by lennartbuit** [comment]
Hmm, so far I can't get it to repro with just how-to-ns, so maybe thats not the offender:

```clj
(set! *print-length* 1)
=> 1

(println '(:require [[a] [b] [c]]))
(:require ...)
=> nil

(println (how-to-ns/format-ns-str "(ns test (:require [a] [b] [c]))" {:require-docstring?      false
                                                                      :sort-clauses?           true
                                                                      ;; should be false, but https://git.io/fhMLm can break code:
                                                                      :allow-refer-all?        true
                                                                      :allow-extra-clauses?    false
                                                                      :align-clauses?          false
                                                                      :import-square-brackets? false}))
(ns test
  (:require
   [a]
   [b]
   [c]))
=> nil
```

**Comment by vemv** [comment]
Thanks for giving it a shot 🍻

Next suspect would be

https://github.com/nedap/formatting-stack/blob/df434ccb4f5bed605e40bcec01a32d0760f5df37/src/formatting_stack/formatters/trivial_ns_duplicates.clj#L139

as it uses pr-str?

**Comment by vemv** [comment]
Looks like this one can be closed
