### ISSUE TITLE
Make `:formatting-stack/ns-aliases` understand a codebase's patterns

### ISSUE THREAD

**Issue by vemv** [nedap/formatting-stack#204]
## Context

While `:formatting-stack/ns-aliases` is useful, it also can be annoying to use in an existing codebase with no particular inclination towards using Sierra's style.

The ns style is sometimes outside one's control e.g. I'm checking out a random repo.

f-s could try to be smarter there and not complain so easily - it is part of the project's spirit to avoid giving a wall of inflexible warnings.

## Suggested task

A given project's `:acceptable-aliases-whitelist` is augmented with the set of aliases that are used in the project and not new (per git: they don't belong to the git status or the git branch diff)

## Acceptance criteria

* `:acceptable-aliases-whitelist` are augmented in a way that doesn't compromise overall accuracy
* the project-wide analysis is cached

**Comment by thumbnail** [comment]
alternatively, with greater configurability we could disable it by default and allow consumers to turn it on in their repo.

**Comment by vemv** [comment]
Sure thing, however what I had in mind is that one f-s can help one use Sierra's style for 'his' code, while not complaining at everything else.

It's pretty common in projects that there's no convention whatsoever for ns aliases (or that the convention is precisely 'do whatever you want').

So that's where a hybrid approach makes sense.
